export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  SERVICES: '/services',
  DASHBOARD: "/dashboard",
  SIGN_IN: "/sign-in",
  FORGOT_PASSWORD: "/forgot-password",
  CREATE_CATEGORY: "/category-list/create",
  CATEGORY_LIST: "/category-list",
  CATEGORY_DETAIL: "/category-list/:id",
  CATEGORY_UPDATE: "/category-list/:id/update",
  USER_ACCOUNTS: "/user-accounts",
  NOT_FOUND: "/404",
  CREATE_PRODUCT: "/product/create",
  PRODUCT_LIST: "/product/list",
  PRODUCT_DETAIL: "/product/:id",
  PRODUCT_UPDATE: "/product/:id/update",
  PRODUCT_LOW_STOCK: "/product/low-stock",
  PRODUCT_INVENTORY: "/product/inventory",
} as const;
