export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  SERVICES: '/services',
  DASHBOARD: "/dashboard",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  USER_ACCOUNTS: "/user-accounts",
  NOT_FOUND: "/404",
  WHITE_LIST: "/white-list",
  PORTFOLIO: "/portfolio",
  BLOG: "/blog",
  CONTACT: "/contact",
  PROFILE: "/profile",
  RESOURCES: "/resources",
  PRODUCTS: "/products",
  HELP: "/help",
  APPOINTMENTS: "/appointments",
  BLOGS: "/blogs",
} as const;
