import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";

import {
  ArrowDownUpIcon,
  BackpackIcon,
  Bell,
  BoxIcon,
  CakeIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeftIcon,
  ChevronsRightIcon,
  ChevronUp,
  ClockIcon,
  Cloud,
  CoffeeIcon,
  ContactIcon,
  CreditCard,
  CrossIcon,
  DockIcon,
  EditIcon,
  EllipsisVerticalIcon,
  Eye,
  EyeOff,
  GrapeIcon,
  HashIcon,
  HeartIcon,
  HelpCircleIcon,
  HotelIcon,
  IceCreamIcon,
  ImageIcon,
  InfoIcon,
  LayoutDashboard,
  ListOrderedIcon,
  LoaderIcon,
  LogOutIcon,
  MailIcon,
  MailPlusIcon,
  MapPinIcon,
  MenuIcon,
  MoonIcon,
  NewspaperIcon,
  Package2Icon,
  PackageIcon,
  PaperclipIcon,
  PauseIcon,
  PhoneIcon,
  PizzaIcon,
  PlaneIcon,
  PlayIcon,
  PlusCircleIcon,
  SandwichIcon,
  SearchIcon,
  Settings2Icon,
  ShoppingBagIcon,
  SmileIcon,
  SquareSplitHorizontalIcon,
  StarsIcon,
  SunIcon,
  Table,
  Trash,
  TruckIcon,
  UserCircle,
  UserIcon,
  UserPenIcon,
  UserPlusIcon,
  UsersIcon,
  ViewIcon,
  WarehouseIcon,
  XIcon,
} from "lucide-react";
import facebook from "./svg/facebook.svg";
import file from "./svg/file.svg";
import github from "./svg/github.svg";
import globe from "./svg/globe.svg";
import google from "./svg/google.svg";
import instagram from "./svg/instagram.svg";
import microsoft from "./svg/microsoft.svg";
import twitter from "./svg/twitter.svg";
import window from "./svg/window.svg";

const IconList = {
  google,
  microsoft,
  github,
  globe,
  file,
  window,
  eye: Eye,
  eyeOff: EyeOff,
  trash: Trash,
  cloud: Cloud,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  layoutDashboard: LayoutDashboard,
  listOrderedIcon: ListOrderedIcon,
  newspaperIcon: NewspaperIcon,
  userCircle: UserCircle,
  userPenIcon: UserPenIcon,
  logOutIcon: LogOutIcon,
  creditCard: CreditCard,
  bell: Bell,
  table: Table,
  sun: SunIcon,
  moon: MoonIcon,
  squareSplitHorizontal: SquareSplitHorizontalIcon,
  search: SearchIcon,
  shoppingBag: ShoppingBagIcon,
  users: UsersIcon,
  mailPlusIcon: MailPlusIcon,
  userPlusIcon: UserPlusIcon,
  arrowDownUp: ArrowDownUpIcon,
  cross: CrossIcon,
  x: XIcon,
  check: CheckIcon,
  chevronsLeft: ChevronsLeftIcon,
  chevronsRight: ChevronsRightIcon,
  plusCircle: PlusCircleIcon,
  calendar: CalendarIcon,
  settings: Settings2Icon,
  dotsVertical: EllipsisVerticalIcon,
  edit: EditIcon,
  view: ViewIcon,
  image: ImageIcon,
  stars: StarsIcon,
  package: Package2Icon,
  hash: HashIcon,
  mail: MailIcon,
  mapPin: MapPinIcon,
  phone: PhoneIcon,
  clock: ClockIcon,
  user: UserIcon,
  calendarDays: CalendarDaysIcon,
  box: BoxIcon,
  warehouse: WarehouseIcon,
  paperclip: PaperclipIcon,
  dock: DockIcon,
  truck: TruckIcon,
  heart: HeartIcon,
  menu: MenuIcon,
  facebook,
  twitter,
  pause: PauseIcon,
  play: PlayIcon,
  cake: CakeIcon,
  pizza: PizzaIcon,
  sandwich: SandwichIcon,
  coffee: CoffeeIcon,
  iceCream: IceCreamIcon,
  grape: GrapeIcon,
  hotel: HotelIcon,
  plane: PlaneIcon,
  smile: SmileIcon,
  backpack: BackpackIcon,
  help: HelpCircleIcon,
  contact: ContactIcon,
  info: InfoIcon,
  loader: LoaderIcon,
  instagram,
};

type SVGAttributes = Partial<SVGProps<SVGSVGElement>>;
type ComponentAttributes = RefAttributes<SVGSVGElement> & SVGAttributes;
interface IconProps extends ComponentAttributes {
  size?: string | number;
  absoluteStrokeWidth?: boolean;
}

export type Icon = ForwardRefExoticComponent<IconProps>;

export const Icons = IconList as Record<keyof typeof IconList, Icon>;
